---
- name: install hyper
  homebrew_cask:
    name: hyper
    state: latest
    accept_external_apps: True
  when: ansible_facts['os_family'] == 'Darwin'

- name: install hyper
  apt:
    deb: https://releases.hyper.is/download/deb
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: setup config
  copy:
    src: hyper.js
    dest: "{{ ansible_facts['env']['HOME'] }}/.hyper.js"
