---
- name: install redis
  homebrew:
    name: redis
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: install redis
  pacman:
    name: redis
    update_cache: yes
    state: present
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- block:

    - name: add redis ppa
      apt_repository:
        repo: 'ppa:chris-lea/redis-server'
        state: present
        update_cache: yes
      tags: redis

    - name: install redis
      apt:
        pkg: redis-server
        state: present
      tags: redis

    - name: start redis
      service:
        name: redis-server
        state: started
        enabled: yes
      tags: redis

  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'
