---
- name: install shellcheck
  homebrew:
    name: shellcheck
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: install shellcheck
  pacman:
    name: shellcheck
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install shellcheck
  apt:
    name: shellcheck
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'
