---
- name: install youtube-dl
  homebrew:
    name: youtube-dl
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: install youtube-dl
  pacman:
    name: youtube-dl
    update_cache: yes
    state: present
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install youtube-dl
  apt:
    name: youtube-dl
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'
