---
- block:

    - name: tap puma/puma
      homebrew_tap:
        name: puma/puma
        state: present

    - name: install puma-dev
      homebrew:
        name: puma/puma/puma-dev
        state: present

    - name: setup puma-dev resolver
      command: "{{ homebrew_path }}/bin/puma-dev -setup"
      args:
        creates: "/etc/resolver/{{ puma_dev_domain }}"
      become: yes
      become_method: sudo

    - name: ensure puma-dev app directory exists
      file:
        path: "{{ puma_dev_dir }}"
        state: directory
        mode: "0755"

    - name: install puma-dev launchd agent
      template:
        src: io.puma.dev.plist.j2
        dest: "{{ ansible_env.HOME }}/Library/LaunchAgents/io.puma.dev.plist"
        mode: "0644"
      notify:
        - reload puma-dev

    - name: link puma-dev apps to ports
      copy:
        content: "{{ item.port }}\n"
        dest: "{{ puma_dev_dir }}/{{ item.name }}"
        mode: "0644"
      with_items: "{{ puma_dev_apps }}"

  when: ansible_facts['os_family'] == 'Darwin'
