---
- hosts: local
  connection: local
  roles:
    - role: mac-setup
      tags: setup
      when: ansible_facts['os_family'] == 'Darwin'
    - role: linux-setup
      tags: setup
      when: ansible_facts['os_family'] == 'Archlinux' or ansible_facts['distribution'] == 'Ubuntu'
    - { role: git, tags: git }
    - { role: git-crypt, tags: git-crypt }
    - { role: ssh, tags: ssh }
    - role: brew
      tags: brew
      when: ansible_facts['os_family'] == 'Darwin'
    - role: cask
      tags: cask
      when: ansible_facts['os_family'] == 'Darwin'
    #- role: mas
    #  tags: mas
    #  when: ansible_facts['os_family'] == 'Darwin'
    - { role: zsh, tags: shell, when: "shell == 'zsh'" }
    - { role: bash, tags: shell, when: "shell == 'bash'" }
    - { role: bash_aliases, tags: shell, when: "shell == 'bash'" }
    - { role: gpg, tags: gpg }
    - { role: rc-files, tags: rc-files }
    - { role: vscode, tags: vscode }
    # - { role: neovim, tags: neovim }
    - { role: tmux, tags: tmux }
    - { role: tig, tags: tig }
    - { role: hh, tags: hh }
    # - { role: insomnia, tags: insomnia }
    - { role: awscli, tags: awscli }
    # - { role: google-chrome, tags: google-chrome }
    - { role: zoom, tags: zoom }
    # - { role: skype, tags: skype }
    - { role: spotify, tags: spotify }
    # - { role: vlc, tags: vlc }
    - { role: mise, tags: mise }
    - { role: yarn, tags: yarn }
    # - { role: go, tags: go }
    # - { role: elixir, tags: elixir }
    # - { role: nginx, tags: nginx }
    - { role: postgres, tags: postgres }
    - { role: redis, tags: redis }
    # - { role: wkhtmltopdf, tags: wkhtmltopdf }
    - { role: terraform, tags: terraform }
    - { role: docker, tags: docker }
    - { role: shellcheck, tags: shellcheck }
    # - { role: youtube-dl, tags: youtube-dl }
    # - { role: vhosts, tags: vhosts }
    - { role: wallpaper, tags: wallpaper }
    - { role: hostname, tags: hostname }
    - { role: forego, tags: forego }
    - { role: kubernetes, tags: kubernetes }
    - { role: warp, tags: warp }
    - { role: superset, tags: superset }
    - { role: ccmenu, tags: ccmenu }
    - role: alfred
      tags: alfred
      when: ansible_facts['os_family'] == 'Darwin'
    - { role: claude-code, tags: claude-code }
