---
- name: copy wallpaper
  copy:
    src: "wallpaper-{{ wallpaper }}.jpg"
    dest: "{{ ansible_facts['env']['HOME'] }}/Pictures/wallpaper.jpg"

- name: set wallpaper
  command: "osascript -e 'tell application \"Finder\" to set desktop picture to POSIX file \"{{ ansible_facts['env']['HOME'] }}/Pictures/wallpaper.jpg\"'"
  when: ansible_facts['os_family'] == 'Darwin'

- block:

    - name: set wallpaper
      command: "gsettings set org.gnome.desktop.background picture-uri 'file://{{ ansible_facts['env']['HOME'] }}/Pictures/wallpaper.jpg'"

    - name: set lockscreen
      command: "gsettings set org.gnome.desktop.screensaver picture-uri 'file://{{ ansible_facts['env']['HOME'] }}/Pictures/wallpaper.jpg'"

  when: ansible_facts['distribution'] == 'Ubuntu' or ansible_facts['os_family'] == 'Archlinux'
