---
- name: install aws-cli
  homebrew:
    name: awscli
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: install aws-cli
  pacman:
    name: aws-cli
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install aws-cli
  apt:
    name: awscli
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'
