---
- block:

    - name: install visual-studio-code
      homebrew_cask:
        name: visual-studio-code
        state: latest
        accept_external_apps: True
      tags: vscode

    - name: Setup Dir
      file:
        dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Code/User"
        state: directory

    - name: Setup Files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - keybindings.json

    - name: setup Settings
      template:
        src: "settings.json.j2"
        dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Code/User/settings.json"

    - name: setup Projects
      template:
        src: "projects.json.j2"
        dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Code/User/projects.json"
      tags: vscode-projects

  when: ansible_facts['os_family'] == 'Darwin'

- block:

    - name: install visual-studio-code
      command: yaourt -S visual-studio-code-bin --noconfirm
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: install visual-studio-code
      apt:
        deb: https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: setup config dir
      file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/Code/User"
        state: directory

    - name: setup Settings
      template:
        src: "settings.json.j2"
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/Code/User/settings.json"

    - name: setup Projects
      template:
        src: "projects.json.j2"
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/Code/User/projects.json"
      tags: vscode-projects

  when: ansible_facts['os_family'] == 'Archlinux' or ansible_facts['distribution'] == 'Ubuntu'

- name: install extensions
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  tags:
    - vscode-extensions
    - vscode
