---
- name: install tig
  homebrew:
    name: tig
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: install tig
  pacman:
    name: tig
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install tig
  apt:
    name: tig
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: copy tigrc
  copy:
    src: "tigrc"
    dest: "{{ ansible_facts['env']['HOME'] }}/.tigrc"
