---
- name: setup ssh dir
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh"
    mode: '0700'
    state: directory

- name: configure 1password ssh agent
  blockinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh/config"
    create: true
    mode: '0600'
    marker: "# {mark} ANSIBLE MANAGED 1PASSWORD SSH AGENT"
    block: |
      Host *
        IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
  when: ansible_facts['os_family'] == 'Darwin'
