---
- block:

    - name: install warp
      homebrew_cask:
        name: warp
        state: present
        accept_external_apps: True
        sudo_password: "{{ ansible_become_pass | default('') }}"

    - name: create warp themes directory
      file:
        path: "{{ ansible_facts['env']['HOME'] }}/.warp/themes"
        state: directory

    - name: copy warp theme
      copy:
        src: "SC-Connie.yaml"
        dest: "{{ ansible_facts['env']['HOME'] }}/.warp/themes/SC-Connie.yaml"

    - name: copy warp theme background
      copy:
        src: "SC-Connie.jpg"
        dest: "{{ ansible_facts['env']['HOME'] }}/.warp/themes/SC-Connie.jpg"

    - name: copy warp keybindings
      copy:
        src: "keybindings.yaml"
        dest: "{{ ansible_facts['env']['HOME'] }}/.warp/keybindings.yaml"

    - name: set warp app icon
      community.general.osx_defaults:
        domain: dev.warp.Warp-Stable
        key: AppIcon
        type: string
        value: '"Original"'

    - name: set warp theme
      community.general.osx_defaults:
        domain: dev.warp.Warp-Stable
        key: Theme
        type: string
        value: '{"Custom":{"name":"SC-Connie","path":"{{ ansible_facts["env"]["HOME"] }}/.warp/themes/SC-Connie.yaml"}}'

  when: ansible_facts['os_family'] == 'Darwin'
