---
- block:

    - name: install mise
      homebrew:
        name: mise
        state: latest

    - name: create mise config directory
      file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/mise"
        state: directory

    - name: setup mise config
      copy:
        src: "config.toml"
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/mise/config.toml"

  when: ansible_facts['os_family'] == 'Darwin'
