---
- name: install wkhtmltopdf
  homebrew_cask:
    name: wkhtmltopdf
    state: present
    accept_external_apps: True
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Darwin'

- name: install wkhtmltopdf
  pacman:
    name: wkhtmltopdf
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install wkhtmltopdf
  apt:
    name: wkhtmltopdf
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'
