---
- name: Is Homebrew present?
  command: which brew
  register: homebrew_installed
  ignore_errors: true
  changed_when: false

- name: Install Homebrew
  command: "ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
  when: "'brew' not in homebrew_installed.stdout"

- name: Add Homebrew Taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_taps | default([]) }}"

- name: Install Homebrew Apps
  homebrew:
    name: "{{ brew_apps }}"
    state: present
