---
- name: install git
  homebrew:
    name: git
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: install git
  pacman:
    name: git
    state: latest
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- block:

    - name: add git ppa
      apt_repository:
        repo: ppa:git-core/ppa
        state: present
        update_cache: yes

    - name: install git
      apt:
        name: git
        state: latest
        update_cache: yes

  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/{{ item }}"
  with_items:
    - .gitignore_global
    - .gitmessage.txt

- name: copy gitconfig
  template:
    src: ".gitconfig"
    dest: "{{ ansible_facts['env']['HOME'] }}/.gitconfig"
