---
- name: install docker
  homebrew:
    name: docker
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: install docker app
  homebrew_cask:
    name: docker
    state: present
    accept_external_apps: True
    sudo_password: "{{ ansible_become_pass | default('') }}"
  when: ansible_facts['os_family'] == 'Darwin'

- name: install docker
  pacman:
    name: docker
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install docker
  apt:
    name: docker
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'
