---
- name: reload puma-dev
  shell: |
    launchctl unload {{ ansible_facts['env'].HOME }}/Library/LaunchAgents/io.puma.dev.plist 2>/dev/null || true
    launchctl load {{ ansible_facts['env'].HOME }}/Library/LaunchAgents/io.puma.dev.plist
