---
- name: create config dir
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
    state: directory

- name: copy initial config
  copy:
    src: init.vim
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim/init.vim"

- name: create autoload dir
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/nvim/autoload"
    state: directory

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim/autoload/plug.vim"

- name: install neovim
  homebrew:
    name: neovim/neovim/neovim
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: install neovim
  pacman:
    name: neovim
    state: latest
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_facts['os_family'] == 'Archlinux'

- name: install neovim
  apt:
    name: neovim
    state: latest
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: make sure bashrc.d folder is present
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc.d"
    state: directory
  when: shell == 'bash'
  tags: shell

- name: make sure zshrc.d folder is present
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.zshrc.d"
    state: directory
  when: shell == 'zsh'
  tags: shell

- name: setup bash config
  copy:
    src: "neovim.bash"
    dest: "{{ ansible_facts['env']['HOME'] }}/.bashrc.d/neovim.bash"
  when: shell == 'bash'
  tags: shell

- name: setup zsh config
  copy:
    src: "neovim.zsh"
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc.d/neovim.zsh"
  when: shell == 'zsh'
  tags: shell
